openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /tournaments/{League}:
    $ref: './paths/tournaments.yaml'
  /games/{Tournament}:
    $ref: './paths/games.yaml'
  /leagues:
    $ref: './paths/leagues.yaml'
  /leagues/{code}:
    $ref: './paths/league_single.yaml'

components:
  schemas:
    Tournament:
      $ref: './components/schemas/ddb/models/tournament.yaml#/Tournament'
    League:
      $ref: './components/schemas/ddb/models/league.yaml#/League'
    Game:
      $ref: './components/schemas/ddb/models/game.yaml#/Game'
    Player:
      $ref: './components/schemas/ddb/models/player.yaml#/Player'
    Team:
      $ref: './components/schemas/ddb/models/team.yaml#/Team'
