openapi: "3.0.2"
info:
  title: Lol Esports Api
  version: "0.0.6"
  description: "League of Legends Esports API"
externalDocs:
  url: https://mckernant1.github.io/lol-openapi/
servers:
  - url: https://api.lol-esports.mckernant1.com
paths:
  /tournaments/{leagueId}:
    $ref: './paths/tournaments.yaml'
  /matches/{tournamentId}:
    $ref: './paths/matches.yaml'
  /leagues:
    $ref: './paths/leagues.yaml'
  /leagues/{leagueId}:
    $ref: './paths/league_single.yaml'
  /players/{teamId}:
    $ref: './paths/players_on_team.yaml'
  /teams:
    $ref: './paths/teams.yaml'
  /teams/{teamId}:
    $ref: './paths/team_single.yaml'


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      description: Default Free API key is CO6gm83RDj3U7LW2uFqKx41n0S834zFi4V7o2fKL
  schemas:
    Tournament:
      $ref: './components/schemas/ddb/models/tournament.yaml#/Tournament'
    League:
      $ref: './components/schemas/ddb/models/league.yaml#/League'
    Game:
      $ref: './components/schemas/ddb/models/match.yaml#/Match'
    Player:
      $ref: './components/schemas/ddb/models/player.yaml#/Player'
    Team:
      $ref: './components/schemas/ddb/models/team.yaml#/Team'

security:
  - ApiKeyAuth: []
