openapi: "3.0.2"
info:
  title: Lol Esports Api
  version: "1.0"
servers:
  - url: https://api.lol-esports.mckernant1.com
paths:
  /tournaments/{League}:
    $ref: './paths/tournaments.yaml'
  /games/{Tournament}:
    $ref: './paths/games.yaml'
  /leagues:
    $ref: './paths/leagues.yaml'
  /leagues/{code}:
    $ref: './paths/league_single.yaml'
  /players/{team}:
    $ref: './paths/players_on_team.yaml'


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    Tournament:
      $ref: './components/schemas/ddb/models/tournament.yaml#/Tournament'
    League:
      $ref: './components/schemas/ddb/models/league.yaml#/League'
    Game:
      $ref: './components/schemas/ddb/models/game.yaml#/Game'
    Player:
      $ref: './components/schemas/ddb/models/player.yaml#/Player'
    Team:
      $ref: './components/schemas/ddb/models/team.yaml#/Team'

security:
  - ApiKeyAuth: []
