version: 0.2


phases:
  install:
    commands:
      - npm install @openapitools/openapi-generator-cli -g
  java:
    commands:
      - openapi-generator-cli generate -g java -i root.yaml -o gen -c config.json -t templates/java
      - cd gen
      - gradle publish
  javascript:
    commands:
      - openapi-generator-cli generate -g javascript -i root.yaml -o gen-js -c config.json -t templates/java
      - cd gen-js
      - npm i
      - npm publish
