version: 0.2


phases:
  install:
    commands:
      - npm install @openapitools/openapi-generator-cli -g
  build:
    commands:
      - openapi-generator-cli generate -g java -i root.yaml -o gen -c config.json -t templates/java
  post_build:
    commands:
      - cd gen
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken)
      - echo $AWS_ACCESS_KEY_ID
      - echo $AWS_SECRET_ACCESS_KEY
      - echo $AWS_SESSION_TOKEN
      - gradle publish
