version: 0.2

phases:
  install:
    commands:
      - npm install @openapitools/openapi-generator-cli -g
      - openapi-generator-cli version-manager set 5.4.0
  build:
    commands:
      - openapi-generator-cli generate -g rust-server -i root.yaml -o gen -c config-rust.json
  post_build:
    commands:
      - cd gen
      - cargo publish
