version: 0.2


phases:
  install:
    commands:
      - npm install @openapitools/openapi-generator-cli -g
  build:
    commands:
      - openapi-generator-cli generate -g java -i root.yaml -o gen -c config.json -t templates/java
  post_build:
    commands:
      - cd gen
      - gradle publish
