version: 0.2

env:
  parameter-store:
    NPM_TOKEN: "npm-token"

phases:
  install:
    commands:
      - npm install @openapitools/openapi-generator-cli -g
      - openapi-generator-cli version-manager set 5.4.0
  pre_build:
    commands:
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - npm whoami
  build:
    commands:
      - openapi-generator-cli generate -g typescript -i root.yaml -o gen-ts -c config-ts.json
  post_build:
    commands:
      - cd gen-ts
      - npm i
      - npm publish
