version: 0.2

env:
  parameter-store:
    CRATES_PUBLISH_KEY: "cratesio-publish"

phases:
  install:
    commands:
      - npm install @openapitools/openapi-generator-cli -g
      - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
      - source "$HOME/.cargo/env"
  pre_build:
    commands:
      - echo $CRATES_PUBLISH_KEY | cargo login
  build:
    commands:
      - openapi-generator-cli generate -g rust -i root.yaml -o gen -c config-rust.json
  post_build:
    commands:
      - cd gen
      - cargo publish
