version: 0.2


env:
  secrets-manager:
    NPM_TOKEN: "npm-token:NPM_TOKEN"

phases:
  install:
    commands:
      - npm install @openapitools/openapi-generator-cli -g
  pre_build:
    commands:
      - echo $NPM_TOKEN
      - npm whoami
  build:
    commands:
      - openapi-generator-cli generate -g java -i root.yaml -o gen -c config.json -t templates/java
      - openapi-generator-cli generate -g javascript -i root.yaml -o gen-js -c config.json -t templates/java
  post_build:
    commands:
      - cd gen
      - gradle publish
      - cd ../gen-js
      - npm i
      - npm publish
